--- !ditz.rubyforge.org,2008-03-06/project 
name: schema-form
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: schema-form
- !ditz.rubyforge.org,2008-03-06/component 
  name: yogo.schema
- !ditz.rubyforge.org,2008-03-06/component 
  name: tests
releases: []

